export const companies = [
    { id: 1, href: "/companies/details/mahy-khoory-group", label: "MAHY Khoory Group", image: "/assets/4_nyqcha.png", video: "/assets/Large-Industrial-Pumping-Structure-Releasing-Waste-2025-12-09-08-06-36-Utc_heqlt4.mp4" },
    { id: 2, href: "/companies/details/mahy-khoory-trading", label: "MAHY Khoory Trading", image: "/assets/pumps-2026-01-05-00-36-52-utc_zqaddp.jpg", video: "/assets/M.A.H.Y._KHOORY_CO._jtklrf.mp4" },
    { id: 3, href: "/companies/details/al-khoory-engineering", label: "Al Khoory Engineering", image: "/assets/WhatsApp_Image_2026-03-02_at_12.16.04_AM_mft26k.jpg", video: "/assets/Worker-Welding-Metal-Structure-2025-12-17-03-36-52-Utc_fasyth.mp4" },
    // { id: 4, label: "EIEME", image: "/assets/EI_bodvyi.jpg", video: "/assets/Emirates_International_j2r7p4.mp4" },
    // { id: 5, label: "GEMD", image: "/gallery/gallery-5.jpg", video: "/assets/GEMD_ijbifl.mp4" },
    // { id: 6, label: "Al Mehwar", image: "/gallery/gallery-6.jpg", video: "/assets/AL_mehwar_zsb9aq.mp4" },
    { id: 7, href: "/companies/details/union-wood-works", label: "Union Wood Works", image: "/assets/electrical-fretsaw-sawdust-and-wooden-bricks-on-vi-2026-01-11-09-19-31-utc_fiyflt.jpg", video: "/assets/uww_jac3pt.mp4" },
    { id: 8, href: "/companies/details/union-paper-mills", label: "Union Paper Mills", image: "/assets/UPM.4_ir521p.jpg", video: "/assets/Union_Paper_Mills_Reel_q14iax.mp4" },
    { id: 9, href: "/companies/details/al-dhafra-paper-manufacturing", label: "Al-Dhafra Paper Manufacturing Company LLC", image: "/assets/WhatsApp_Image_2026-03-02_at_12.19.34_AM_sdjdxi.jpg", video: "/assets/ALDHAFRA_qdxvk2.mp4" },
    { id: 10, href: "/companies/details/mahy-khoory-automotive", label: "MAHY Khoory Automotive", image: "/assets/WhatsApp_Image_2026-03-02_at_12.24.38_AM_nrygeh.jpg", video: "/assets/Mka_Mkm_fapg90.mp4" },
    { id: 11, href: "/companies/details/mahy-khoory-motors", label: "MAHY Khoory Motors", image: "/assets/Introducing_the_JAECOO_7__A_Premier_Urban_Off-Road_SUV_f56xof.png", video: "/assets/MKM_uk3jfm.mp4" },
    { id: 12, href: "/companies/details/greenland-general-transport", label: "Greenland General Transport", image: "/assets/fleet-of-white-delivery-trucks-parked-in-a-lot-2026-01-09-11-55-05-utc_is9mnb.png", video: "/assets/0205_tlzogv.mp4" },
    { id: 13, href: "/companies/details/recyclable-waste-management-division", label: "Recyclable Waste Management Division", image: "/assets/industrial_recycling_yard_at_a_professional_waste_management_facility.jpg_mi3ghv.jpg", video: "/assets/RWMD_lrlpyc.mp4" },
    { id: 14, href: "/companies/details/al-dhafra-waste-collection", label: "Al Dhafra Waste Collection", image: "/assets/Paper_Mills_iyg61d.jpg", video: "/assets/0205-waste_wiqnq1.mp4" },
    { id: 15, href: "/companies/details/around-continent-waste-collection", label: "Green Arabia", image: "/assets/modern_waste_collection_truck_with_Green.jpg_znuzj3.png", video: "/assets/Around_Continent_Waste_Collection_Green_Arabia_mgylog.mp4" },
    { id: 16, href: "/companies/details/al-etihad-waste-management-services-llc", label: "Al Etihad Waste Management", image: "/assets/crane-at-garbage-collection-center-2026-01-05-23-01-32-utc_iirlx6.jpg", video: "/assets/Garbage-Truck-Collects-Waste-At-A-Landfill-Site-In-2025-12-17-16-53-21-Utc_wkkepo.mp4" },
    { id: 17, href: "/companies/details/pearl-marina", label: "Pearl Marina Hotel Apartments", image: "/assets/Dubai-pearl-marina.jpg_jormq7.jpg", video: "/assets/Pearl_Marina_Hotel_Apartments_xyartc.mp4" },
    { id: 18, href: "/companies/details/market-restaurant", label: "Market Restaurant & Cafe", image: "/assets/Picture4_ai73lx.png", video: "/assets/The_Market_Resteraunt_p8ttqn.mp4" },
    { id: 19, href: "/companies/details/national-paper-industry", label: "National Paper Industries", image: "/assets/the-tech-prepare-cardboard-sheet-with-precision-be-2026-01-07-05-43-25-utc_z8btjk.jpg", video: "/assets/National_Paper_Industries_bhhmav.mp4" },
    { id: 20, href: "/companies/details/senan-industry", label: "Senan Industries", image: "/assets/portrait-of-young-professional-heavy-industry-engi-2026-01-06-10-33-07-utc_g2vf6s.jpg", video: "/assets/Senan_Industry_Llc_q5fd3z.mp4" },
    { id: 21, href: "/companies/details/pure-energy-construction", label: "Pure Energy Construction LLC", image: "/assets/STEEL_CONSTRUCTION_tvs7ap.jpg", video: "/assets/two-workers-install-a-solar-panel-2025-12-17-22-23-18-utc_qybojv.mp4" },
    { id: 22, href: "/companies/details/clean-earth-llc", label: "Clean Energy Solution", image: "/assets/solar-panels-against-blue-sky-2026-01-09-09-16-02-utc_1_mgox1d.png", video: "/assets/Green_Energy_ht2c5n.mp4" },
    { id: 23, href: "/companies/details/union-sustainable-packaging", label: "Union Sustainable Packaging Solutions", image: "/assets/young-workers-working-in-a-woodworking-factory-us-2026-01-07-01-52-42-utc_df67nz.jpg", video: "/assets/Carpenter-Assembling-Wooden-Pallets-In-Slow-Motion-2026-01-22-11-16-40-Utc_mqnzdf.mp4" },
    { id: 24, href: "/companies/details/solid-waste-management-division", label: "Solid Waste Management", image: "/assets/conveyor-belt-on-slag-heap-2026-01-05-05-57-04-utc_sdbjl6.jpg", video: "/assets/Solid_Waste_Management_Division_imhdko.mp4" }
];

