import { getStateCountryCode } from "@/lib/utils/country";

export const PASSPORT_NUMBER_MAX_LENGTH = 15;
export const PERSON_NAME_MIN_LENGTH = 1;
export const UAE_DIALING_CODE = "+971";
export const PASSPORT_NUMBER_REGEX = new RegExp(
  `^[A-Za-z0-9]{1,${PASSPORT_NUMBER_MAX_LENGTH}}$`,
);

export function sanitizePassportNumber(value = "") {
  return value.replace(/[^A-Za-z0-9]/g, "").slice(0, PASSPORT_NUMBER_MAX_LENGTH);
}

export function mergeAreaCodeWithPhoneNumber(areaCode = "", phoneNumber = "") {
  const normalizedAreaCode = String(areaCode || "").trim();
  const normalizedPhoneNumber = String(phoneNumber || "").trim();

  if (!normalizedAreaCode) {
    return normalizedPhoneNumber;
  }

  return `${normalizedAreaCode}${normalizedPhoneNumber}`;
}

const createUAEAreaCodeOption = (areaCode) => ({
  value: areaCode,
  label: areaCode,
  countryCode: "00971",
});

export const UAE_TELEPHONE_AREA_CODES = ["2", "3", "4", "6", "7", "9"].map(
  createUAEAreaCodeOption,
);

export const UAE_MOBILE_AREA_CODES = ["50", "52", "54", "55", "56", "57"].map(
  createUAEAreaCodeOption,
);

export const CUSTOMER_TYPES = [
  { value: "organization", label: "Organization" },
  { value: "individual", label: "Person" },
];

export const CUSTOMER_CLASSIFICATION_GROUPS = [
  { value: "credit", label: "Credit" },
  { value: "onetime", label: "OneTime" },
];

export const NAME_PREFIXES = [
    { value: "mr", label: "Mr." },
    { value: "mrs", label: "Mrs." },
    { value: "ms", label: "Ms." },
    { value: "dr", label: "Dr." },
    { value: "prof", label: "Prof." },
];

export const CURRENCIES = [
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "USD", label: "USD - US Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
];

export const VAT_TYPES = [
  { value: "with_trn", label: "With TRN" },
  { value: "without_trn", label: "Without TRN" },
];

export const PAYMENT_TERMS = [
  { value: "cash", label: "Cash" },
  { value: "30_days", label: "30 Days" },
  { value: "60_days", label: "60 Days" },
];

export const PAYMENT_METHODS = [
  { value: "CASH", label: "CASH" },
  { value: "CDC", label: "CDC" },
  { value: "ELECTRONIC", label: "ELECTRONIC" },
  { value: "PDC", label: "PDC" },
];

export const SUBSEGMENTS = [];

export const ADDRESS_BOOKS = [{ value: "RealEstate", label: "RealEstate" }];

export const ADDRESS_TYPES = [
  { value: "billing", label: "Billing" },
  { value: "delivery", label: "Delivery" },
  { value: "both", label: "Both" },
];

// All Countries
export const COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "North Korea" },
  { value: "KR", label: "South Korea" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "UAE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

// States by country
export const STATES_BY_COUNTRY = {
  UAE: [
    { value: "abu_dhabi", label: "Abu Dhabi" },
    { value: "dubai", label: "Dubai" },
    { value: "sharjah", label: "Sharjah" },
    { value: "ajman", label: "Ajman" },
    { value: "ras_al_khaimah", label: "Ras Al Khaimah" },
    { value: "fujairah", label: "Fujairah" },
    { value: "umm_al_quwain", label: "Umm Al Quwain" },
  ],
  US: [
    { value: "AL", label: "Alabama" },
    { value: "AK", label: "Alaska" },
    { value: "AZ", label: "Arizona" },
    { value: "AR", label: "Arkansas" },
    { value: "CA", label: "California" },
    { value: "CO", label: "Colorado" },
    { value: "CT", label: "Connecticut" },
    { value: "DE", label: "Delaware" },
    { value: "FL", label: "Florida" },
    { value: "GA", label: "Georgia" },
    { value: "HI", label: "Hawaii" },
    { value: "ID", label: "Idaho" },
    { value: "IL", label: "Illinois" },
    { value: "IN", label: "Indiana" },
    { value: "IA", label: "Iowa" },
    { value: "KS", label: "Kansas" },
    { value: "KY", label: "Kentucky" },
    { value: "LA", label: "Louisiana" },
    { value: "ME", label: "Maine" },
    { value: "MD", label: "Maryland" },
    { value: "MA", label: "Massachusetts" },
    { value: "MI", label: "Michigan" },
    { value: "MN", label: "Minnesota" },
    { value: "MS", label: "Mississippi" },
    { value: "MO", label: "Missouri" },
    { value: "MT", label: "Montana" },
    { value: "NE", label: "Nebraska" },
    { value: "NV", label: "Nevada" },
    { value: "NH", label: "New Hampshire" },
    { value: "NJ", label: "New Jersey" },
    { value: "NM", label: "New Mexico" },
    { value: "NY", label: "New York" },
    { value: "NC", label: "North Carolina" },
    { value: "ND", label: "North Dakota" },
    { value: "OH", label: "Ohio" },
    { value: "OK", label: "Oklahoma" },
    { value: "OR", label: "Oregon" },
    { value: "PA", label: "Pennsylvania" },
    { value: "RI", label: "Rhode Island" },
    { value: "SC", label: "South Carolina" },
    { value: "SD", label: "South Dakota" },
    { value: "TN", label: "Tennessee" },
    { value: "TX", label: "Texas" },
    { value: "UT", label: "Utah" },
    { value: "VT", label: "Vermont" },
    { value: "VA", label: "Virginia" },
    { value: "WA", label: "Washington" },
    { value: "WV", label: "West Virginia" },
    { value: "WI", label: "Wisconsin" },
    { value: "WY", label: "Wyoming" },
  ],
  IN: [
    { value: "AP", label: "Andhra Pradesh" },
    { value: "AR", label: "Arunachal Pradesh" },
    { value: "AS", label: "Assam" },
    { value: "BR", label: "Bihar" },
    { value: "CG", label: "Chhattisgarh" },
    { value: "GA", label: "Goa" },
    { value: "GJ", label: "Gujarat" },
    { value: "HR", label: "Haryana" },
    { value: "HP", label: "Himachal Pradesh" },
    { value: "JH", label: "Jharkhand" },
    { value: "KA", label: "Karnataka" },
    { value: "KL", label: "Kerala" },
    { value: "MP", label: "Madhya Pradesh" },
    { value: "MH", label: "Maharashtra" },
    { value: "MN", label: "Manipur" },
    { value: "ML", label: "Meghalaya" },
    { value: "MZ", label: "Mizoram" },
    { value: "NL", label: "Nagaland" },
    { value: "OD", label: "Odisha" },
    { value: "PB", label: "Punjab" },
    { value: "RJ", label: "Rajasthan" },
    { value: "SK", label: "Sikkim" },
    { value: "TN", label: "Tamil Nadu" },
    { value: "TS", label: "Telangana" },
    { value: "TR", label: "Tripura" },
    { value: "UP", label: "Uttar Pradesh" },
    { value: "UK", label: "Uttarakhand" },
    { value: "WB", label: "West Bengal" },
  ],
  SA: [
    { value: "riyadh", label: "Riyadh" },
    { value: "makkah", label: "Makkah" },
    { value: "madinah", label: "Madinah" },
    { value: "eastern", label: "Eastern Province" },
    { value: "asir", label: "Asir" },
    { value: "tabuk", label: "Tabuk" },
    { value: "hail", label: "Hail" },
    { value: "northern", label: "Northern Borders" },
    { value: "jazan", label: "Jazan" },
    { value: "najran", label: "Najran" },
    { value: "bahah", label: "Al-Bahah" },
    { value: "jawf", label: "Al-Jawf" },
    { value: "qassim", label: "Qassim" },
  ],
  GB: [
    { value: "ENG", label: "England" },
    { value: "SCT", label: "Scotland" },
    { value: "WLS", label: "Wales" },
    { value: "NIR", label: "Northern Ireland" },
  ],
  CA: [
    { value: "AB", label: "Alberta" },
    { value: "BC", label: "British Columbia" },
    { value: "MB", label: "Manitoba" },
    { value: "NB", label: "New Brunswick" },
    { value: "NL", label: "Newfoundland and Labrador" },
    { value: "NS", label: "Nova Scotia" },
    { value: "ON", label: "Ontario" },
    { value: "PE", label: "Prince Edward Island" },
    { value: "QC", label: "Quebec" },
    { value: "SK", label: "Saskatchewan" },
  ],
  AU: [
    { value: "NSW", label: "New South Wales" },
    { value: "VIC", label: "Victoria" },
    { value: "QLD", label: "Queensland" },
    { value: "WA", label: "Western Australia" },
    { value: "SA", label: "South Australia" },
    { value: "TAS", label: "Tasmania" },
    { value: "ACT", label: "Australian Capital Territory" },
    { value: "NT", label: "Northern Territory" },
  ],
  PK: [
    { value: "punjab", label: "Punjab" },
    { value: "sindh", label: "Sindh" },
    { value: "kpk", label: "Khyber Pakhtunkhwa" },
    { value: "balochistan", label: "Balochistan" },
    { value: "islamabad", label: "Islamabad Capital Territory" },
  ],
};

// Helper function to get states for a country
export function getStatesForCountry(countryCode) {
  return STATES_BY_COUNTRY[getStateCountryCode(countryCode)] || [];
}

// Keep old STATES for backwards compatibility
export const STATES = STATES_BY_COUNTRY.UAE || [];

// All Country Codes
export const COUNTRY_CODES = [
  { value: "+93", label: "+93 (Afghanistan)" },
  { value: "+355", label: "+355 (Albania)" },
  { value: "+213", label: "+213 (Algeria)" },
  { value: "+376", label: "+376 (Andorra)" },
  { value: "+244", label: "+244 (Angola)" },
  { value: "+54", label: "+54 (Argentina)" },
  { value: "+374", label: "+374 (Armenia)" },
  { value: "+61", label: "+61 (Australia)" },
  { value: "+43", label: "+43 (Austria)" },
  { value: "+994", label: "+994 (Azerbaijan)" },
  { value: "+973", label: "+973 (Bahrain)" },
  { value: "+880", label: "+880 (Bangladesh)" },
  { value: "+375", label: "+375 (Belarus)" },
  { value: "+32", label: "+32 (Belgium)" },
  { value: "+501", label: "+501 (Belize)" },
  { value: "+229", label: "+229 (Benin)" },
  { value: "+975", label: "+975 (Bhutan)" },
  { value: "+591", label: "+591 (Bolivia)" },
  { value: "+387", label: "+387 (Bosnia)" },
  { value: "+267", label: "+267 (Botswana)" },
  { value: "+55", label: "+55 (Brazil)" },
  { value: "+673", label: "+673 (Brunei)" },
  { value: "+359", label: "+359 (Bulgaria)" },
  { value: "+226", label: "+226 (Burkina Faso)" },
  { value: "+257", label: "+257 (Burundi)" },
  { value: "+855", label: "+855 (Cambodia)" },
  { value: "+237", label: "+237 (Cameroon)" },
  { value: "+1", label: "+1 (Canada/US)" },
  { value: "+238", label: "+238 (Cape Verde)" },
  { value: "+236", label: "+236 (Central African Republic)" },
  { value: "+235", label: "+235 (Chad)" },
  { value: "+56", label: "+56 (Chile)" },
  { value: "+86", label: "+86 (China)" },
  { value: "+57", label: "+57 (Colombia)" },
  { value: "+269", label: "+269 (Comoros)" },
  { value: "+242", label: "+242 (Congo)" },
  { value: "+506", label: "+506 (Costa Rica)" },
  { value: "+385", label: "+385 (Croatia)" },
  { value: "+53", label: "+53 (Cuba)" },
  { value: "+357", label: "+357 (Cyprus)" },
  { value: "+420", label: "+420 (Czech Republic)" },
  { value: "+45", label: "+45 (Denmark)" },
  { value: "+253", label: "+253 (Djibouti)" },
  { value: "+593", label: "+593 (Ecuador)" },
  { value: "+20", label: "+20 (Egypt)" },
  { value: "+503", label: "+503 (El Salvador)" },
  { value: "+240", label: "+240 (Equatorial Guinea)" },
  { value: "+291", label: "+291 (Eritrea)" },
  { value: "+372", label: "+372 (Estonia)" },
  { value: "+251", label: "+251 (Ethiopia)" },
  { value: "+679", label: "+679 (Fiji)" },
  { value: "+358", label: "+358 (Finland)" },
  { value: "+33", label: "+33 (France)" },
  { value: "+241", label: "+241 (Gabon)" },
  { value: "+220", label: "+220 (Gambia)" },
  { value: "+995", label: "+995 (Georgia)" },
  { value: "+49", label: "+49 (Germany)" },
  { value: "+233", label: "+233 (Ghana)" },
  { value: "+30", label: "+30 (Greece)" },
  { value: "+502", label: "+502 (Guatemala)" },
  { value: "+224", label: "+224 (Guinea)" },
  { value: "+245", label: "+245 (Guinea-Bissau)" },
  { value: "+592", label: "+592 (Guyana)" },
  { value: "+509", label: "+509 (Haiti)" },
  { value: "+504", label: "+504 (Honduras)" },
  { value: "+36", label: "+36 (Hungary)" },
  { value: "+354", label: "+354 (Iceland)" },
  { value: "+91", label: "+91 (India)" },
  { value: "+62", label: "+62 (Indonesia)" },
  { value: "+98", label: "+98 (Iran)" },
  { value: "+964", label: "+964 (Iraq)" },
  { value: "+353", label: "+353 (Ireland)" },
  { value: "+972", label: "+972 (Israel)" },
  { value: "+39", label: "+39 (Italy)" },
  { value: "+225", label: "+225 (Ivory Coast)" },
  { value: "+81", label: "+81 (Japan)" },
  { value: "+962", label: "+962 (Jordan)" },
  { value: "+254", label: "+254 (Kenya)" },
  { value: "+686", label: "+686 (Kiribati)" },
  { value: "+850", label: "+850 (North Korea)" },
  { value: "+82", label: "+82 (South Korea)" },
  { value: "+965", label: "+965 (Kuwait)" },
  { value: "+996", label: "+996 (Kyrgyzstan)" },
  { value: "+856", label: "+856 (Laos)" },
  { value: "+371", label: "+371 (Latvia)" },
  { value: "+961", label: "+961 (Lebanon)" },
  { value: "+266", label: "+266 (Lesotho)" },
  { value: "+231", label: "+231 (Liberia)" },
  { value: "+218", label: "+218 (Libya)" },
  { value: "+423", label: "+423 (Liechtenstein)" },
  { value: "+370", label: "+370 (Lithuania)" },
  { value: "+352", label: "+352 (Luxembourg)" },
  { value: "+853", label: "+853 (Macau)" },
  { value: "+389", label: "+389 (Macedonia)" },
  { value: "+261", label: "+261 (Madagascar)" },
  { value: "+265", label: "+265 (Malawi)" },
  { value: "+60", label: "+60 (Malaysia)" },
  { value: "+960", label: "+960 (Maldives)" },
  { value: "+223", label: "+223 (Mali)" },
  { value: "+356", label: "+356 (Malta)" },
  { value: "+692", label: "+692 (Marshall Islands)" },
  { value: "+222", label: "+222 (Mauritania)" },
  { value: "+230", label: "+230 (Mauritius)" },
  { value: "+52", label: "+52 (Mexico)" },
  { value: "+691", label: "+691 (Micronesia)" },
  { value: "+373", label: "+373 (Moldova)" },
  { value: "+377", label: "+377 (Monaco)" },
  { value: "+976", label: "+976 (Mongolia)" },
  { value: "+382", label: "+382 (Montenegro)" },
  { value: "+212", label: "+212 (Morocco)" },
  { value: "+258", label: "+258 (Mozambique)" },
  { value: "+95", label: "+95 (Myanmar)" },
  { value: "+264", label: "+264 (Namibia)" },
  { value: "+674", label: "+674 (Nauru)" },
  { value: "+977", label: "+977 (Nepal)" },
  { value: "+31", label: "+31 (Netherlands)" },
  { value: "+64", label: "+64 (New Zealand)" },
  { value: "+505", label: "+505 (Nicaragua)" },
  { value: "+227", label: "+227 (Niger)" },
  { value: "+234", label: "+234 (Nigeria)" },
  { value: "+47", label: "+47 (Norway)" },
  { value: "+968", label: "+968 (Oman)" },
  { value: "+92", label: "+92 (Pakistan)" },
  { value: "+680", label: "+680 (Palau)" },
  { value: "+970", label: "+970 (Palestine)" },
  { value: "+507", label: "+507 (Panama)" },
  { value: "+675", label: "+675 (Papua New Guinea)" },
  { value: "+595", label: "+595 (Paraguay)" },
  { value: "+51", label: "+51 (Peru)" },
  { value: "+63", label: "+63 (Philippines)" },
  { value: "+48", label: "+48 (Poland)" },
  { value: "+351", label: "+351 (Portugal)" },
  { value: "+974", label: "+974 (Qatar)" },
  { value: "+40", label: "+40 (Romania)" },
  { value: "+7", label: "+7 (Russia - Kazakhstan)" },
  { value: "+250", label: "+250 (Rwanda)" },
  { value: "+966", label: "+966 (Saudi Arabia)" },
  { value: "+221", label: "+221 (Senegal)" },
  { value: "+381", label: "+381 (Serbia)" },
  { value: "+248", label: "+248 (Seychelles)" },
  { value: "+232", label: "+232 (Sierra Leone)" },
  { value: "+65", label: "+65 (Singapore)" },
  { value: "+421", label: "+421 (Slovakia)" },
  { value: "+386", label: "+386 (Slovenia)" },
  { value: "+677", label: "+677 (Solomon Islands)" },
  { value: "+252", label: "+252 (Somalia)" },
  { value: "+27", label: "+27 (South Africa)" },
  { value: "+211", label: "+211 (South Sudan)" },
  { value: "+34", label: "+34 (Spain)" },
  { value: "+94", label: "+94 (Sri Lanka)" },
  { value: "+249", label: "+249 (Sudan)" },
  { value: "+597", label: "+597 (Suriname)" },
  { value: "+268", label: "+268 (Eswatini)" },
  { value: "+46", label: "+46 (Sweden)" },
  { value: "+41", label: "+41 (Switzerland)" },
  { value: "+963", label: "+963 (Syria)" },
  { value: "+886", label: "+886 (Taiwan)" },
  { value: "+992", label: "+992 (Tajikistan)" },
  { value: "+255", label: "+255 (Tanzania)" },
  { value: "+66", label: "+66 (Thailand)" },
  { value: "+670", label: "+670 (Timor-Leste)" },
  { value: "+228", label: "+228 (Togo)" },
  { value: "+676", label: "+676 (Tonga)" },
  { value: "+1868", label: "+1868 (Trinidad)" },
  { value: "+216", label: "+216 (Tunisia)" },
  { value: "+90", label: "+90 (Turkey)" },
  { value: "+993", label: "+993 (Turkmenistan)" },
  { value: "+688", label: "+688 (Tuvalu)" },
  { value: "+256", label: "+256 (Uganda)" },
  { value: "+380", label: "+380 (Ukraine)" },
  { value: "+971", label: "+971 (UAE)" },
  { value: "+44", label: "+44 (UK)" },
  { value: "+598", label: "+598 (Uruguay)" },
  { value: "+998", label: "+998 (Uzbekistan)" },
  { value: "+678", label: "+678 (Vanuatu)" },
  { value: "+379", label: "+379 (Vatican)" },
  { value: "+58", label: "+58 (Venezuela)" },
  { value: "+84", label: "+84 (Vietnam)" },
  { value: "+967", label: "+967 (Yemen)" },
  { value: "+260", label: "+260 (Zambia)" },
  { value: "+263", label: "+263 (Zimbabwe)" },
  { value: "+1268", label: "+1268 (Antigua and Barbuda)" },
  { value: "+1242", label: "+1242 (Bahamas)" },
  { value: "+1246", label: "+1246 (Barbados)" },
  { value: "+243", label: "+243 (Democratic Republic of the Congo)" },
  { value: "+1767", label: "+1767 (Dominica)" },
  { value: "+1809", label: "+1809 (Dominican Republic)" },
  { value: "+1473", label: "+1473 (Grenada)" },
  { value: "+1876", label: "+1876 (Jamaica)" },
  { value: "+1869", label: "+1869 (Saint Kitts and Nevis)" },
  { value: "+1758", label: "+1758 (Saint Lucia)" },
  { value: "+1784", label: "+1784 (Saint Vincent and the Grenadines)" },
  { value: "+685", label: "+685 (Samoa)" },
  { value: "+378", label: "+378 (San Marino)" },
  { value: "+239", label: "+239 (Sao Tome and Principe)" },
];

const COUNTRY_CODE_ALIASES = {
  UAE: "UAE",
  "United States": "Canada/US",
  "United States of America": "Canada/US",
  Canada: "Canada/US",
  "Cabo Verde": "Cape Verde",
  Czechia: "Czech Republic",
  "Cote d'Ivoire": "Ivory Coast",
  "Bosnia and Herzegovina": "Bosnia",
  "North Macedonia": "Macedonia",
  Eswatini: "Eswatini",
  Kazakhstan: "Russia - Kazakhstan",
  Russia: "Russia - Kazakhstan",
  "Congo (Republic of the)": "Congo",
  "Trinidad and Tobago": "Trinidad",
  "United Kingdom": "UK",
  "Vatican City": "Vatican",
};

const COUNTRY_DIALING_CODE_OVERRIDES = {
  "Antigua and Barbuda": "+1268",
  Bahamas: "+1242",
  Barbados: "+1246",
  "Democratic Republic of the Congo": "+243",
  Dominica: "+1767",
  "Dominican Republic": "+1809",
  Grenada: "+1473",
  Jamaica: "+1876",
  "Saint Kitts and Nevis": "+1869",
  "Saint Lucia": "+1758",
  "Saint Vincent and the Grenadines": "+1784",
  Samoa: "+685",
  "San Marino": "+378",
  "Sao Tome and Principe": "+239",
};

function normalizeCountryName(country = "") {
  return String(country)
    .replace(/^[^\w]+/, "")
    .trim()
    .toLowerCase();
}

export function getDialingCodeForCountry(country) {
  const override = COUNTRY_DIALING_CODE_OVERRIDES[country];
  if (override) return override;

  const normalizedCountry = normalizeCountryName(
    COUNTRY_CODE_ALIASES[country] || country,
  );

  const match = COUNTRY_CODES.find((item) => {
    const labelCountry = item.label.match(/\((.*)\)/)?.[1] || "";
    return normalizeCountryName(labelCountry) === normalizedCountry;
  });

  return match?.value || UAE_DIALING_CODE;
}

// Helper function to get cities for a country (simplified - you can expand this)
export function getCitiesForCountry(countryCode) {
  // Return empty array - City is now a text field
  return [];
}

// Keep UAE_CITIES for backwards compatibility
export const UAE_CITIES = [
  { value: "dubai", label: "Dubai" },
  { value: "abu_dhabi", label: "Abu Dhabi" },
  { value: "sharjah", label: "Sharjah" },
  { value: "ajman", label: "Ajman" },
  { value: "ras_al_khaimah", label: "Ras Al Khaimah" },
  { value: "fujairah", label: "Fujairah" },
  { value: "umm_al_quwain", label: "Umm Al Quwain" },
];

// Vendor Groups
export const VENDOR_GROUPS = [
  { value: "group1", label: "Group 1" },
  { value: "group2", label: "Group 2" },
  { value: "group3", label: "Group 3" },
];
